import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    "mqtt-radar-connector": "./src/app.ts",
  },
  banner:
    "#!/usr/bin/env node\n// This file is generated by tsdown. Do not edit directly.\n// Last generated: " +
    new Date().toISOString() +
    "\n",
  outDir: "./dist",
  format: "esm",
  platform: "node",
  target: "node20",
  // Produce .mjs so Node treats it as ESM regardless of package.json "type"
  outExtensions: () => ({ js: ".mjs" }),
  // Bundle everything — this is a standalone CLI binary
  noExternal: [/.*/],
  clean: true,
  sourcemap: false,
});
